github:
  client:
    clientId: 77412eedeaee983a2b2a
    clientSecret: bfaa22073f7ba2b1e2376d502fd6bc7fa9cd1fe8
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
server:
  port: 8085
  tomcat:
    uri-encoding: utf-8
spring:
  data:
    neo4j:
      uri: bolt://localhost:17687
      username: neo4j
      password: root
#cas:
#  sign-out-filters: /logout
#  auth-filters: /*
#  validate-filters: /*
#  request-wrapper-filters: /*
#  assertion-filters: /*
#  cas-server-login-url: http://10.168.0.187:8080/login
#  cas-server-url-prefix: http://10.168.0.187:8080
#  redirect-after-validation: true
#  use-session: true
#  server-name: http://localhost:8085

security:
  cas:
    server:
      base-url: http://10.168.0.187:8080
      protocol-version: 2
    service:
      resolution-mode: dynamic
      paths:
        login: /login/cas
    enabled: true


#      cas:
#        server:
#          host:
#            url: http://10.168.0.187:8080
#            login_url: ${cas.server.host.url}/login
#            logout_url: ${cas.server.host.url}/logout?service=